name: deploy-prd

on:
  push:
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "build.gradle"
      - "settings.gradle"
      - "Dockerfile.prd"
    branches:
      - deploy

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      branch: prd
      branch_upper: PRD
      tag_prefix: v-prd-
      dockerfile: Dockerfile.prd
      instance_env: prd
    secrets:
      ENV_CONTENT: ${{ secrets.ENV_CONTENT }}
      DB_NETWORK_NAME: ${{ secrets.DB_NETWORK_NAME }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_ZONE: ${{ secrets.GCP_ZONE }}
      TK_GITHUB_ACCESS_TOKEN: ${{ secrets.TK_GITHUB_ACCESS_TOKEN }}
      TK_GITHUB_ACCESS_TOKEN_OWNER: ${{ secrets.TK_GITHUB_ACCESS_TOKEN_OWNER }}